project:
  type: website
  output-dir: docs
website:
  title: "Liam Gilson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      -projectpage.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
editor: visual

