project:
  type: website
  output-dir: docs
website:
  title: "Liam Gilson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projectpage.qmd
      - Free4All.qmd
      - Resume.qmd

format:
  html:
    theme: 
      - minty
      - styles.scss
    toc: true
    page-layout: full
editor: visual

