---
title: "Baseball"
---

Baseball has always been one of the most important things for me. I started playing baseball around the age of 6 years old in my backyard. My earliest memory of baseball is trying to hit homeruns over a small fence in our garden with a wiffle ball. My first year of little league is something I'll never forget. I was instantly one of the most skilled little kids, and I led my team of 8 and 9 year old's to win the championship.

The next year I was one of only 2 kids to get brought up to the older kids league at the age of 10. Here I met my coach and great friend Jim Gamble. Playing at this higher level skyrocketed my skillset, and pushed me to play with kids bigger and stronger than me.

I played baseball every single year until I entered college, where I finally gave it up almost 13 years after playing with mom in the back yard.

As a shy kid from up in the mountains, Baseball was my way to socialize and meet new friends. Many of the people I played ball with are still some of my closest friends. Baseball was a huge source of confidence in my younger days, and it was the first thing that I ever really excelled at.

Baseball has given me some of my greatest memories and friends, and I cannot thank it enough. It also taught me to believe in myself and it taught me what hard work means. But most importantly it taught me how to be level headed and in control of my emotions. Baseball has taught me more about life than baseball itself. I would like to thank my coaches Hernan Granados, Andy Isdahl, Paige Dumont, Doc Quirici, and most importantly my Mother and Father.

![My first year of little league where I gained my love for baseball (bottom left) My third year of little league where I first played with my best friend Stacy, who is in the background (center) Travel ball around the age of 14 (top left) Me and the boys after a clutch walk off win versus our rivals senior year of High School (top right) My MVP award from my senior year of High school. (bottom right)](pics/BaseballPics.PNG){width="583"}
