---
title: "Project page"
---

Since coming to UCSB I have been able to work on some super cool projects!

One of my most interesting projects I have worked on is a grant application for a river restoration project. The project is taking place on Coyote Creek, in Ventura County. Coyote Creek is a tributary of the Ventura river, and proceeds the Lake Casitas Dam. This area is probematic beacuse for two reasons; The Thomas Fire of 2017 and the Lake Casitas Dam. In short, the dam significantly reduces flow rates and sediment connectivity. Meanwhile, the charred Red Mountain pushes incredible amounts of sediment into the river channel. The result is sediment piling up over 10 feet above agreed upon heights, which in turn floods the community on a yearly basis. My team visited in the dry months and the one road in and out of the community was flooded around 4 inches high.

This was a very cool project because its a real grant application! we submitted it to the necessary officials and are hoping for an answer back soon.

NOTE: this application is not perfect, and was NOT the final grant application we submitted. However it is very close.

You can preview or download the full proposal below:

<iframe src="/GrantApplication/GrantApplication.PDF" width="100%" height="500px">

This browser does not support PDFs. Please <a href="/papers/my_grant.pdf">download the PDF</a> instead.

</iframe>

Liam Gilson
